# Stage that builds the application, a prerequisite for the running stage
FROM maven:3.8.6-eclipse-temurin-11 as build

# Vaadin 23 uses webpack 4, which fails on Node 17+ unless the legacy OpenSSL
# provider is enabled.
ENV NODE_OPTIONS="--openssl-legacy-provider"

RUN apt-get update -qq \
  && apt-get install -qq --no-install-recommends ca-certificates curl gnupg git python3 make g++ \
  && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
  && apt-get update -qq \
  && apt-get install -qq --no-install-recommends nodejs \
  && rm -rf /var/lib/apt/lists/*

# Stop running as root at this point
RUN useradd -m myuser
WORKDIR /usr/src/app/
RUN chown myuser:myuser /usr/src/app/
USER myuser

# Copy pom.xml and prefetch dependencies so a repeated build can continue from the next step with existing dependencies
COPY --chown=myuser pom.xml ./
RUN mvn dependency:go-offline -Pproduction

# Copy all needed project files to a folder
COPY --chown=myuser:myuser src src
COPY --chown=myuser:myuser frontend frontend
COPY --chown=myuser:myuser react-frontend react-frontend
COPY --chown=myuser:myuser package.json ./
COPY --chown=myuser:myuser tsconfig.json types.d.ts webpack.generated.js ./

# Using * after the files that are autogenerated so that so build won't fail if they are not yet created
COPY --chown=myuser:myuser package-lock.json* pnpm-lock.yaml* webpack.config.js* ./

# Build the React SPA and bundle it under /react
RUN cd react-frontend && npm ci && npm run build
RUN mkdir -p src/main/resources/static/react && cp -r react-frontend/dist/* src/main/resources/static/react/

# Build the production package, assuming that we validated the version before so no need for running tests again
RUN mvn clean package -DskipTests -Pproduction

# Running stage: the part that is used for running the application
FROM eclipse-temurin:11-jre
COPY --from=build /usr/src/app/target/*.jar /usr/app/app.jar
RUN useradd -m myuser
USER myuser
ENV PORT=8020
EXPOSE 8020
CMD java -jar /usr/app/app.jar
